AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for MixSubmit

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: (Required) Enter dev, prod. Default is dev.
    AllowedValues:
      - dev
      - prod
  MixBucketName:
    Type: String
    Default: omni-mixes
    Description: (Required) Enter the bucket name. Default is omni-mixes
    AllowedPattern: ^[a-z0-9-]+$

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: dotnet6
    Architectures:
      - x86_64
    CodeUri: ./src/MixSubmit
    Timeout: 10

Resources:
  MixSubmitApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Cors:
        AllowMethods: "'GET,POST'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'*'"
  
  MixBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MixBucketName
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - Date
  
  MixSubmitFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: MixSubmit::MixSubmit.Function::functionHandler
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref MixBucketName
      Environment:
        Variables:
          BUCKET: !Ref MixBucketName
      Events:
        MixSubmit:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref MixSubmitApi

Outputs:
  MixSubmitApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${MixSubmitApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
  MixSubmitFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt MixSubmitFunction.Arn
  MixSubmitFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt MixSubmitFunctionRole.Arn
